export const csvjson = [
	{
		name: "Aasimar",
		cr: "1/2",
		xp: 200,
		race: "Aasimar",
		class: "cleric 1",
		alignment: "NG",
		size: "Medium",
		type: "outsider",
		subType: "(native)",
		initiative: 0,
		senses: "darkvision 60 ft.; Perception +5",
		aura: "",
		ac: "15, touch 10, flat-footed 15",
		acMods: "(+5 armor)",
		hp: 11,
		hitDie: "(1d8+3)",
		hpMods: "",
		fortSave: 4,
		refSave: 0,
		willSave: 5,
		saveMods: "",
		defensiveAbilities: "",
		dr: "",
		immune: "",
		resist: "acid 5, cold 5, electricity 5",
		sr: "",
		weaknesses: "",
		speed: "30 ft. (20 ft. in armor)",
		speedMods: "",
		melee: "heavy mace -1 (1d8-1)",
		ranged: "light crossbow +0 (1d8/19-20)",
		space: "5 ft.",
		reach: "5 ft.",
		specialAttacks:
			"channel positive energy (5/day, 1d6, DC 12); rebuke death (1d4+1, 6/day); touch of good (6/day)",
		spellLikeAbilities: "Spell-Like Abilities (CL 1st) 1/day-daylight",
		spellsKnown: "",
		spellsPrepared:
			"Spells Prepared (CL 1st) 1st-bless, command (DC 14), protection from evilD 0 (at will)-detect magic, guidance, stabilize",
		spellDomains: "Good, Healing",
		abilityScores: "Str 8, Dex 10, Con 14, Int 13, Wis 17, Cha 14",
		baseAtk: 0,
		cmb: "-1",
		cmd: "9",
		feats: "Turn Undead",
		skills: "Diplomacy +8, Heal +7, Knowledge (religion) +5",
		racialMods: "+2 Diplomacy, +2 Perception",
		languages: "Celestial, Common, Draconic",
		sq: "",
		environment: "any land",
		organization: "solitary, pair, or team (3-6)",
		treasure:
			"NPC gear (scale mail, heavy mace, light crossbow with 10 bolts, other treasure)",
		descriptionVisual:
			"This supernaturally beautiful woman looks human, yet emanates a strange sense of calm and benevolence.",
		group: "",
		source: "PFRPG Bestiary",
		isTemplate: 0,
		specialAbilities: "",
		description:
			"Aasimars are humans with a signif icant amount of celestial or other good outsider blood in their ancestry. Aasimars are not always good, but it is a natural tendency for them, and they gravitate to good faiths or organizations associated with celestials. Aasimar heritage can hide for generations, only to appear suddenly in the child of two apparently human parents. Most societies interpret aasimar births as good omens. Aasimars look mostly human except for some minor physical trait that reveals their unusual heritage. Typical aasimar features are hair that shines like metal, unusual eye or skin color, or even glowing golden halos. Aasimar Characters Aasimars are defined by class levels-they do not possess racial Hit Dice. Aasimars have the following racial traits. +2 Charisma, +2 Wisdom: Aasimars are insightful, confident, and personable. Normal Speed: Aasimars have a base speed of 30 feet. Darkvision: Aasimars can see in the dark up to 60 feet. Skilled: Aasimars have a +2 racial bonus on Diplomacy and Perception checks. Spell-Like Ability: Aasimars can use daylight once per day as a spell-like ability (caster level equals the aasimar's class level). Celestial Resistance: Aasimars have acid resistance 5, cold resistance 5, and electricity resistance 5. Languages: Aasimars begin play speaking Common and Celestial. Aasimars with high Intelligence scores can choose any of the following bonus languages: Draconic, Dwarven, Elven, Gnome, Half ling, and Sylvan.",
		bloodline: "",
		prohibitedSchools: "",
		beforeCombat: "",
		duringCombat: "",
		morale: "",
		gear: "",
		otherGear: "",
		note: "",
		characterFlag: 1,
		companionFlag: 0,
		canFly: 0,
		canClimb: 0,
		canBurrow: 0,
		canSwim: 0,
		canWalk: 1,
		templatesApplied: "",
		offenseNote: "",
		baseStatistics: "",
		extractsPrepared: "",
		ageCategory: "adult",
		dontUseRacialHD: 1,
		variantParent: "",
		mystery: "",
		classArchetypes: "",
		patron: "",
		alternateNameForm: "",
		statisticsNote: "",
		link: "",
		monsterId: 20,
		mythicRating: 0,
		mythic: 0,
	},
	{
		name: "Goblin",
		cr: "1/3",
		xp: 135,
		race: "Goblin",
		class: "warrior 1",
		alignment: "NE",
		size: "Small",
		type: "humanoid",
		subType: "(goblinoid)",
		initiative: 6,
		senses: "darkvision 60 ft.; Perception -1",
		aura: "",
		ac: "16, touch 13, flat-footed 14",
		acMods: "(+2 armor, +2 Dex, +1 shield, +1 size)",
		hp: 6,
		hitDie: "(1d10+1)",
		hpMods: "",
		fortSave: 3,
		refSave: 2,
		willSave: -1,
		saveMods: "",
		defensiveAbilities: "",
		dr: "",
		immune: "",
		resist: "",
		sr: "",
		weaknesses: "",
		speed: "30 ft.",
		speedMods: "",
		melee: "short sword +2 (1d4/19-20)",
		ranged: "short bow +4 (1d4/x3)",
		space: "5 ft.",
		reach: "5 ft.",
		specialAttacks: "",
		spellLikeAbilities: "",
		spellsKnown: "",
		spellsPrepared: "",
		spellDomains: "",
		abilityScores: "Str 11, Dex 15, Con 12, Int 10, Wis 9, Cha 6",
		baseAtk: 1,
		cmb: "0",
		cmd: "12",
		feats: "Improved Initiative",
		skills: "Ride +10, Stealth +10, Swim +4",
		racialMods: "+4 Ride, +4 Stealth",
		languages: "Goblin",
		sq: "",
		environment: " temperate forest and plains (usually coastal regions)",
		organization:
			"gang (4-9), warband (10-16 with goblin dog mounts), or tribe (17+ plus 100% noncombatants; 1 sergeant of 3rd level per 20 adults; 1 or 2 lieutenants of 4th or 5th level; 1 leader of 6th-8th level; and 10-40 goblin dogs, wolves, or worgs)",
		treasure:
			"NPC gear (leather armor, light wooden shield, short sword, short bow with 20 arrows, other treasure)",
		descriptionVisual:
			"This creature stands barely three feet tall, its scrawny, humanoid body dwarfed by its wide, ungainly head.",
		group: "",
		source: "PFRPG Bestiary",
		isTemplate: 0,
		specialAbilities: "",
		description:
			"Goblins prefer to dwell in caves, amid large and dense thickets of thistles and brambles, or in structures built and then abandoned by others. Very few goblins have the drive to build structures of their own. Coastlines are favored, as goblins are quite fond of sifting through junk and flotsam in an unending quest to find treasures among the refuse of more civilized races. Goblin hatred runs deep, and few things inspire their wrath more than gnomes (who have long fought against goblins), horses (who frighten goblins tremendously), and regular dogs (whom goblins regard as pale imitations of goblin dogs). Goblins are also quite superstitious, and treat magic with a fawning mixture of awe and fear. They have the habit of ascribing magic to the mundane as well, with fire and writing both taking on mystical power in goblin society. Fire is much loved by goblins for its capacity to wreak great destruction and because it doesn't require size or strength to wield, but written words are hated. Goblins believe that writing steals words out of your head, and as a result of this belief, goblins are universally illiterate. Goblins are voracious and can eat their body weight in food daily without growing fat. Goblin lairs always have numerous storerooms and larders. While they prefer human and gnome flesh, a goblin won't turn down any food-except, perhaps, vegetables. Goblin Characters Goblins are defined by their class levels-they do not possess racial Hit Dice. All goblins have the following racial traits. -2 Strength, +4 Dexterity, -2 Charisma: Goblins are fast, but weak and unpleasant to be around. Small: Goblins are Small creatures and gain a +1 size bonus to their AC, a +1 size bonus on attack rolls, a -1 penalty to their CMB and CMD, and a +4 size bonus on Stealth checks. Fast: Goblins are fast for their size, and have a base speed of 30 feet. Darkvision: Goblins can see in the dark up to 60 feet. Skilled: +4 racial bonus on Ride and Stealth checks. Languages: Goblins begin play speaking Goblin. Goblins with high Intelligence scores can choose any of these bonus languages: Common, Draconic, Dwarven, Gnoll, Gnome, Halfling, Orc.",
		bloodline: "",
		prohibitedSchools: "",
		beforeCombat: "",
		duringCombat: "",
		morale: "",
		gear: "",
		otherGear: "",
		note: "",
		characterFlag: 1,
		companionFlag: 0,
		canFly: 0,
		canClimb: 0,
		canBurrow: 0,
		canSwim: 0,
		canWalk: 1,
		templatesApplied: "",
		offenseNote: "",
		baseStatistics: "",
		extractsPrepared: "",
		ageCategory: "adult",
		dontUseRacialHD: 1,
		variantParent: "",
		mystery: "",
		classArchetypes: "",
		patron: "",
		alternateNameForm: "",
		statisticsNote: "",
		link: "",
		monsterId: 214,
		mythicRating: 0,
		mythic: 0,
	},
	{
		name: "Human Skeleton",
		cr: "1/3",
		xp: 135,
		race: "",
		class: "",
		alignment: "NE",
		size: "Medium",
		type: "undead",
		subType: "",
		initiative: 6,
		senses: "darkvision 60 ft.; Perception +0",
		aura: "",
		ac: "16, touch 12, flat-footed 14",
		acMods: "(+2 armor, +2 Dex, +2 natural)",
		hp: 4,
		hitDie: "(1d8)",
		hpMods: "",
		fortSave: 0,
		refSave: 2,
		willSave: 2,
		saveMods: "",
		defensiveAbilities: "",
		dr: "5/bludgeoning",
		immune: "cold, undead traits",
		resist: "",
		sr: "",
		weaknesses: "",
		speed: "30 ft.",
		speedMods: "",
		melee: "broken scimitar +0 (1d6), claw -3 (1d4+1) or 2 claws +2 (1d4+2)",
		ranged: "",
		space: "5 ft.",
		reach: "5 ft.",
		specialAttacks: "",
		spellLikeAbilities: "",
		spellsKnown: "",
		spellsPrepared: "",
		spellDomains: "",
		abilityScores: "Str 15, Dex 14, Con -, Int -, Wis 10, Cha 10",
		baseAtk: 0,
		cmb: "2",
		cmd: "14",
		feats: "Improved InitiativeB Gear broken chain shirt, broken scimitar",
		skills: "",
		racialMods: "",
		languages: "",
		sq: "",
		environment: " any",
		organization: "any",
		treasure: "none",
		descriptionVisual:
			"The pile of bones suddenly stirs, rising up to take on a human shape. Its long, bony fingers reach out to claw at the living.",
		group: "Skeleton",
		source: "PFRPG Bestiary",
		isTemplate: 1,
		specialAbilities: "",
		description:
			"Skeletons are the animated bones of the dead, brought to unlife through foul magic. While most skeletons are mindless automatons, they still possess an evil cunning imparted to them by their animating force-a cunning that allows them to wield weapons and wear armor. Creating a Skeleton \"Skeleton\" is an acquired template that can be added to any corporeal creature (other than an undead) that has a skeletal system (referred to hereafter as the base creature). Challenge Rating: Depends on Hit Dice, as follows: HD CR XP 1/2 1/6 65 1 1/3 135 2-3 1 400 4-5 2 600 6-7 3 800 8-9 4 1,200 10-11 5 1,600 12-14 6 2,400 15-17 7 3,200 18-20 8 4,800 Alignment: Always neutral evil. Type: The creature's type changes to undead. It retains any subtype except for alignment subtypes (such as good) and subtypes that indicate kind (such as giant). It does not gain the augmented subtype. It uses all the base creature's statistics and special abilities except as noted here. Armor Class: Natural armor bonus changes as follows: Skeleton Size N atural Armor Bonus Tiny or smaller +0 Small +1 Medium or Large +2 Huge +3 Gargantuan +6 Colossal +10 Hit Dice: A skeleton drops any HD gained from class levels and changes racial HD to d8s. Creatures without racial HD are treated as if they have 1 racial HD. If the creature has more than 20 Hit Dice, it can't be made into a skeleton by the animate dead spell. A skeleton uses its Cha modifier (instead of its Con modifier) to determine bonus hit points. Saves: Base save bonuses are Fort +1/3 HD, Ref +1/3 HD, and Will +1/2 HD + 2. Defensive Abilities: A skeleton loses the base creature's defensive abilities and gains DR 5/bludgeoning and immunity to cold. It also gains all of the standard immunities and traits possessed by undead creatures. Speed: A winged skeleton can't use its wings to fly. If the base creature flew magically, so can the skeleton. All other movement types are retained. Attacks: A skeleton retains all the natural weapons, manufactured weapon attacks, and weapon proficiencies of the base creature, except for attacks that can't work without flesh. A creature with hands gains one claw attack per hand; the skeleton can strike with each of its claw attacks at its full attack bonus. A claw attack deals damage depending on the skeleton's size (see pages 301-302). If the base creature already had claw attacks with its hands, use the skeleton claw damage only if it's better. Special Attacks: A skeleton retains none of the base creature's special attacks. Abilities: A skeleton's Dexterity increases by +2. It has no Constitution or Intelligence score, and its Wisdom and Charisma scores change to 10. BAB: A skeleton's base attack bonus is equal to 3/4 of its Hit Dice. Skills: A skeleton loses all skill ranks possessed by the base creature and gains none of its own. Feats: A skeleton loses all feats possessed by the base creature and gains Improved Initiative as a bonus feat. Special Qualities: A skeleton loses most special qualities of the base creature. It retains any extraordinary special qualities that improve its melee or ranged attacks. Environment: Any, usually the same as base creature. Organization: Any. Treasure: Generally none, although sometimes a skeleton's creator arms it with magical armor or weapons. Variant Skeletons Numerous variant skeletons exist, such as those whose bones burn with an unending fire and those who drip with gore and reassemble themselves over time. Both of these variant skeletons can be created using animate dead, but they count as twice their normal number of Hit Dice per casting. Once controlled, they count normally against the controller's limit. Perhaps the most dangerous variant skeleton, though, is the skeletal champion. This skeleton retains its intellect, and often any class levels it possessed in life. A skeletal champion cannot be created with animate dead-these potent undead only arise under rare conditions similar to those that cause the manifestation of ghosts or via rare and highly evil rituals. Each of the following skeleton types modifies the base skeleton in a few key ways. Except as noted, these variations can be stacked with one another-it's possible to have a bloody burning skeletal champion. Bloody Skeleton A bloody skeleton is coated in a slick layer of blood and gore infused with negative energy. This gore allows the skeleton to reform and heal itself. In addition to the changes for the skeleton template, make the following adjustments to the base creature. Challenge Rating: As a normal skeleton + 1. Fast Healing: A bloody skeleton has fast healing equal to 1 per 2 Hit Dice it possesses (minimum 1). Saves: A bloody skeleton gains channel resistance +4. Abilities: A bloody skeleton's Charisma is 14. Special Qualities: A bloody skeleton gains the deathless special quality. Deathless (Su): A bloody skeleton is destroyed when reduced to 0 hit points, but it returns to unlife 1 hour later at 1 hit point, allowing its fast healing thereafter to resume healing it. A bloody skeleton can be permanently destroyed if it is destroyed by positive energy, if it is reduced to 0 hit points in the area of a bless or hallow spell, or if its remains are sprinkled with a vial of holy water. Burning Skeleton A burning skeleton is surrounded by an aura of flames that deals fire damage to those it strikes. In addition to the changes for the skeleton template, make the following adjustments to the base creature. Challenge Rating: As a normal skeleton + 1. Aura: Burning skeletons possess a fiery aura. Fiery Aura (Ex): Creatures adjacent to a burning skeleton take 1d6 points of fire damage at the start of their turn. Anyone striking a burning skeleton with an unarmed strike or natural attack takes 1d6 points of fire damage. Defensive Abilities: Burning skeletons lose their immunity to cold but gain immunity to fire. A burning skeleton gains vulnerability to cold damage. Melee Attacks: A burning skeleton's melee attacks (including both those made with a natural weapon and those made with a manufactured weapon) deal an additional 1d6 points of fire damage. Abilities: A burning skeleton's Charisma is 12. Special Qualities: A burning skeleton gains fiery death. Fiery Death (Su): A burning skeleton explodes into a burst of flame when it dies. Anyone adjacent to the skeleton when it is destroyed takes 1d6 points of fire damage per 2 Hit Dice the skeleton possessed (minimum 1d6). A Ref lex save (DC = 10 + 1/2 the skeleton's Hit Dice + the skeleton's Cha bonus) halves this damage.",
		bloodline: "",
		prohibitedSchools: "",
		beforeCombat: "",
		duringCombat: "",
		morale: "",
		gear: "",
		otherGear: "",
		note: "",
		characterFlag: 0,
		companionFlag: 0,
		canFly: 0,
		canClimb: 0,
		canBurrow: 0,
		canSwim: 0,
		canWalk: 1,
		templatesApplied: "",
		offenseNote: "",
		baseStatistics: "",
		extractsPrepared: "",
		ageCategory: "adult",
		dontUseRacialHD: 0,
		variantParent: "",
		mystery: "",
		classArchetypes: "",
		patron: "",
		alternateNameForm: "",
		statisticsNote: "",
		link: "",
		monsterId: 321,
		mythicRating: 0,
		mythic: 0,
	},
	{
		name: "Slime Mold",
		cr: "2",
		xp: 600,
		race: "",
		class: "",
		alignment: "N",
		size: "Large",
		type: "ooze",
		subType: "",
		initiative: -1,
		senses: "Perception -5",
		aura: "",
		ac: "8, touch 8, flat-footed 8",
		acMods: "(-1 Dex, -1 size)",
		hp: 28,
		hitDie: "(3d8+15)",
		hpMods: "",
		fortSave: 6,
		refSave: 0,
		willSave: -4,
		saveMods: "",
		defensiveAbilities: "",
		dr: "",
		immune: "ooze traits",
		resist: "fire 10",
		sr: "",
		weaknesses: "",
		speed: "20 ft.",
		speedMods: "",
		melee: "slam +4 (1d6+4 plus disease)",
		ranged: "",
		space: "10 ft.",
		reach: "10 ft.",
		specialAttacks: "engulf (DC 14, 1d6+4 bludgeoning plus disease)",
		spellLikeAbilities: "",
		spellsKnown: "",
		spellsPrepared: "",
		spellDomains: "",
		abilityScores: "Str 16, Dex 8, Con 21, Int -, Wis 1, Cha 1",
		baseAtk: 2,
		cmb: "6",
		cmd: "15 (can't be tripped)",
		feats: "",
		skills: "",
		racialMods: "",
		languages: "",
		sq: "freeze",
		environment: " temperate forests",
		organization: "single or infestation (2-5)",
		treasure: "none",
		descriptionVisual:
			"What at first seemed to be a carpet of fungi and mushrooms suddenly stirs to life, surging forward with a reek of decay.",
		group: "",
		source: "PFRPG Bestiary 2",
		isTemplate: 0,
		specialAbilities:
			"Disease (Ex) Fungal rot: Slam-contact; save Fortitude DC 16; onset 1 day; frequency 1/day; effect 1d2 Str damage and 1 Con damage and fatigue; cure 1 save. Any creature that touches a slime mold with an unarmed strike or a natural attack is also exposed to this foul disease. The save DC is Constitution-based.",
		description:
			"Slime molds are revolting oozes that wallow in rot and decay. A perfect example of symbiosis, each slime mold is covered in a thick garden of fungi, mildew, and toadstools, which helps it blend in with the surroundings. As ambush hunters, they can lie silently in wait for days at a time, surging into frenzied movement as soon as prey comes within reach. Most commonly encountered in deep forests, variations have adapted to life in caverns and sewers as well. They lack any ability to digest food, and rely entirely on their symbiotic fungal gardens to break down any organic matter they find into easily absorbed compost and decay. The molds and mushrooms that coat the ooze in turn receive ample food supplies, and over countless generations, many have developed into deadly variations of the forest or cave fungi from which they evolved. This fungal breakdown is in many ways akin to a disease-known as fungal rot, it can kill if allowed to progress for long. Those who succumb to fungal rot become tired and listless. Eventually, paralysis sets in and the victim's flesh begins to blacken and decay, running from the body in liquid streams that the slime mold can easily absorb. In a somewhat nauseating turnabout, certain creatures find the unusual fungus that grows upon a slime mold to be quite tasty, and these creatures actively hunt slime molds to devour their gardens-although they take care to avoid actual contact with the mold itself unless they happen to be immune to disease.  Slime molds are ovoid in shape, growing up to 12 feet in length and weighing more than 600 pounds. Their substance is normally a sickly greenish-brown, with the coloration varying depending on their environment and how recently they've fed. They instinctually keep their coating of fungus and other vegetable detritus exposed above them, granting the slime mold a distinctive, undulating gait rather than the fluid movement of most oozes.  To reproduce, slime molds split off small patches of their bodies whenever they encounter thick beds of fungi or mold. Over several months, these tiny blobs acclimate to the rot and absorb each another, until a single slime mold (with the young creature simple template) sprouts its own garden and begins hunting live prey.",
		bloodline: "",
		prohibitedSchools: "",
		beforeCombat: "",
		duringCombat: "",
		morale: "",
		gear: "",
		otherGear: "",
		note: "",
		characterFlag: 0,
		companionFlag: 0,
		canFly: 0,
		canClimb: 0,
		canBurrow: 0,
		canSwim: 0,
		canWalk: 1,
		templatesApplied: "",
		offenseNote: "",
		baseStatistics: "",
		extractsPrepared: "",
		ageCategory: "adult",
		dontUseRacialHD: 0,
		variantParent: "",
		mystery: "",
		classArchetypes: "",
		patron: "",
		alternateNameForm: "",
		statisticsNote: "",
		link: "",
		monsterId: 1352,
		mythicRating: 0,
		mythic: 0,
	},
	{
		name: "Black Pudding",
		cr: "7",
		xp: 3200,
		race: "",
		class: "",
		alignment: "N",
		size: "Huge",
		type: "ooze",
		subType: "",
		initiative: -5,
		senses: "blindsight 60 ft.; Perception -5",
		aura: "",
		ac: "3, touch 3, flat-footed 3",
		acMods: "(-2 size, -5 Dex)",
		hp: 105,
		hitDie: "(10d8+60)",
		hpMods: "",
		fortSave: 9,
		refSave: -2,
		willSave: -2,
		saveMods: "",
		defensiveAbilities: "split, ooze traits",
		dr: "",
		immune: "",
		resist: "",
		sr: "",
		weaknesses: "",
		speed: "20 ft., climb 20 ft.",
		speedMods: "",
		melee: "slam +8 (2d6+4 plus 2d6 acid plus grab)",
		ranged: "",
		space: "15 ft.",
		reach: "10 ft.",
		specialAttacks: "constrict (2d6+4 plus 2d6 acid), corrosion",
		spellLikeAbilities: "",
		spellsKnown: "",
		spellsPrepared: "",
		spellDomains: "",
		abilityScores: "Str 16, Dex 1, Con 22, Int -, Wis 1, Cha 1",
		baseAtk: 7,
		cmb: "+12 (+16 grapple)",
		cmd: "17 (27 vs. bull rush, can't be tripped)",
		feats: "",
		skills: "Climb +11",
		racialMods: "",
		languages: "",
		sq: "ooze traits, suction",
		environment: " any underground",
		organization: "solitary",
		treasure: "none",
		descriptionVisual:
			"This black, amorphous blob piles up on itself, a quivering mound of midnight sludge that glistens darkly before surging forward.",
		group: "Pudding",
		source: "PFRPG Bestiary",
		isTemplate: 0,
		specialAbilities:
			"Acid (Ex) A black pudding secretes a digestive acid that dissolves organic material and metal quickly, but does not affect stone.  Each time a creature suffers damage from a black pudding's acid, its clothing and armor take the same amount of damage from the acid. A DC 21 Reflex save prevents damage to clothing and armor. A metal or wooden weapon that strikes a black pudding takes 2d6 acid damage unless the weapon's wielder succeeds on a DC 21 Reflex save. If a black pudding remains in contact with a wooden or metal object for 1 full round, it inflicts 21 points of acid damage (no save) to the object. The save DCs are Constitution-based.  Corrosion (Ex) An opponent that is being constricted by a black pudding suffers a -4 penalty on Reflex saves made to resist acid damage applying to clothing and armor.  Split (Ex) Slashing and piercing weapons deal no damage to a black pudding. Instead, the creature splits into two identical puddings, each with half of the original's current hit points (round down). A pudding with 10 hit points or less cannot be further split and dies if reduced to 0 hit points.  Suction (Ex) The black pudding can create powerful suction against any surface as it climbs, allowing it to cling to inverted surfaces with ease. A black pudding can establish or release suction as a swift action, and as long as it is using suction, it moves at half speed. Because of the suction, a black pudding's CMD score gets a +10 circumstance bonus to resist bull rush, awesome blows, and other attacks and effects that attempt to physically move it from its location.",
		description:
			"Black puddings are the scavengers of the underworld, constantly on the lookout for a meal. They can sense organic or metallic objects within 60 feet and mindlessly attack such items or beings until they are dissolved or the ooze is killed. A black pudding reproduces by breaking off a piece of its body and forming a new, smaller black pudding, which grows to full size in 1 month's time. Some of the more intelligent creatures in the underworld use black puddings as natural garbage disposals, creating stone pits to house the pudding and throwing organic refuse or foes in as needed.  Larger specimens of black puddings have been encountered in the deepest parts of the world, with Gargantuan individuals having up to 30 HD. Other colored puddings are rumored to exist, with white ones living in the arctic, brown ones living in swamps, and tan ones living in deserts.",
		bloodline: "",
		prohibitedSchools: "",
		beforeCombat: "",
		duringCombat: "",
		morale: "",
		gear: "",
		otherGear: "",
		note: "",
		characterFlag: 0,
		companionFlag: 0,
		canFly: 0,
		canClimb: 1,
		canBurrow: 0,
		canSwim: 0,
		canWalk: 1,
		templatesApplied: "",
		offenseNote: "",
		baseStatistics: "",
		extractsPrepared: "",
		ageCategory: "adult",
		dontUseRacialHD: 0,
		variantParent: "",
		mystery: "",
		classArchetypes: "",
		patron: "",
		alternateNameForm: "",
		statisticsNote: "",
		link: "",
		monsterId: 49,
		mythicRating: 0,
		mythic: 0,
	},
	{
		name: "Slime Mold",
		cr: "3",
		xp: 800,
		race: "",
		class: "",
		alignment: "N",
		size: "Large",
		type: "ooze",
		subType: "(fungus)",
		initiative: -1,
		senses: "blindsight 60 ft; Perception +0",
		aura: "",
		ac: "8, touch 8, flat-footed 8",
		acMods: "(-1 Dex, -1 size, +0 natural)",
		hp: 38,
		hitDie: "(4d8+20)",
		hpMods: "",
		fortSave: 6,
		refSave: 0,
		willSave: -4,
		saveMods: "",
		defensiveAbilities: "",
		dr: "",
		immune: "ooze traits",
		resist: "",
		sr: "",
		weaknesses: "",
		speed: "20 ft.",
		speedMods: "",
		melee: "slam +3 (1d8+1 plus disease plus grab)",
		ranged: "",
		space: "10 ft.",
		reach: "5 ft.",
		specialAttacks: "engulf (1d8+1)",
		spellLikeAbilities: "",
		spellsKnown: "",
		spellsPrepared: "",
		spellDomains: "",
		abilityScores: "Str 13, Dex 8, Con 21, Int -, Wis 1, Cha 1",
		baseAtk: 3,
		cmb: "+5 (+9 grapple)",
		cmd: "14 (can't be tripped)",
		feats: "",
		skills: "",
		racialMods: "",
		languages: "",
		sq: "camouflage",
		environment: " temperate forests",
		organization: "solitary",
		treasure: "none",
		descriptionVisual:
			"A large but colorful grove of small mushrooms and other tiny plants sprout upon a wide swath of moss.",
		group: "",
		source: "Tome of Horrors Complete",
		isTemplate: 0,
		specialAbilities:
			"Camouflage (Ex) A slime mold looks like a normal patch of fungus when at rest. It takes a DC 20 Perception check to notice it before it attacks. Anyone with ranks in Survival or Knowledge (nature) can use one of those skills instead of Perception to notice the ooze. Dwarves can use stonecunning to notice the subterranean version.  Disease (Ex) Fungal rot: Slam-contact; save Fort DC 17; onset 1 day; effect 1d3 Con and 1d3 Str damage; cure 1 save. The save DC is Constitution-based.  Engulf (Ex) A slime mold can wrap a creature of up to one size smaller in its body as a standard action. If a slime mold succeeds a Combat Maneuver check to grapple an opponent, it establishes a hold and deals slam damage each round the hold is maintained. Attacks that hit an engulfing slime mold deal half their damage to the monster and half to the trapped victim.",
		description:
			"Slime molds are found in forests, swamps, and underground; any place natural fungi and mold grows. A slime mold lies dormant among the growths soaking nutrients from them, and waiting for living creatures to wander too close to it.  Slime molds are often mistaken for plant creatures because their forms are completely covered with molds, fungi, and in particular mushrooms of varying hues, shapes, and sizes. This gives the monster the appearance of an undulating mass of plant matter when actuality they are a rare form of non-acidic ooze. Something in the creature's protoplasmic substance causes mushrooms, molds, mosses, and other fungal plants to take root and grow on its surface in a symbiotic relationship.  A slime mold attacks from surprise anytime it detects a living creature within 10 feet of it. It lashes out with a pseudopod and then attempts to wrap its body around the victim. The slime mold relies on its natural ability to appear as a patch of mushrooms to foil potential prey. Slime molds inflict an opponent with fungal rot if they hit with a slam attack.  Fungal rot causes a darkening of the skin and small patches of fungus and mold to sprout at random locations on the victim's body.  Copyright Notice Author Scott Greene.",
		bloodline: "",
		prohibitedSchools: "",
		beforeCombat: "",
		duringCombat: "",
		morale: "",
		gear: "",
		otherGear: "",
		note: "",
		characterFlag: 0,
		companionFlag: 0,
		canFly: 0,
		canClimb: 0,
		canBurrow: 0,
		canSwim: 0,
		canWalk: 1,
		templatesApplied: "",
		offenseNote: "",
		baseStatistics: "",
		extractsPrepared: "",
		ageCategory: "adult",
		dontUseRacialHD: 0,
		variantParent: "",
		mystery: "",
		classArchetypes: "",
		patron: "",
		alternateNameForm: "",
		statisticsNote: "",
		link: "",
		monsterId: 3022,
		mythicRating: 0,
		mythic: 0,
	},
	{
		name: "Fast Zombie",
		cr: "1/2",
		xp: 200,
		race: "",
		class: "",
		alignment: "NE",
		size: "Medium",
		type: "undead",
		subType: "",
		initiative: 0,
		senses: "darkvision 60 ft.; Perception +0",
		aura: "",
		ac: "14, touch 10, flat-footed 12",
		acMods: "(+2 Dex, +2 natural)",
		hp: 12,
		hitDie: "(2d8+3)",
		hpMods: "",
		fortSave: 0,
		refSave: 2,
		willSave: 3,
		saveMods: "",
		defensiveAbilities: "",
		dr: "",
		immune: "undead traits",
		resist: "",
		sr: "",
		weaknesses: "",
		speed: "40 ft.",
		speedMods: "",
		melee: "2 slams +4 (1d6+4)",
		ranged: "",
		space: "5 ft.",
		reach: "5 ft.",
		specialAttacks: "quick strikes",
		spellLikeAbilities: "",
		spellsKnown: "",
		spellsPrepared: "",
		spellDomains: "",
		abilityScores: "Str 17, Dex 14, Con -, Int -, Wis 10, Cha 10",
		baseAtk: 1,
		cmb: "4",
		cmd: "16",
		feats: "ToughnessB",
		skills: "",
		racialMods: "",
		languages: "",
		sq: "",
		environment: " any",
		organization: "any",
		treasure: "none",
		descriptionVisual:
			"This walking corpse wears only a few soiled rags, its flesh rotting off its bones as it stumbles forward with unnatural quickness, arms outstretched.",
		group: "Zombie",
		source: "d20pfsrd",
		isTemplate: 0,
		specialAbilities:
			"Quick Strikes (Ex) Whenever a fast zombie takes a full-attack action, it can make one additional slam attack at its highest base attack bonus.",
		description:
			"Unlike the standard, plodding zombie, a fast zombie moves with a supernatural quickness.",
		bloodline: "",
		prohibitedSchools: "",
		beforeCombat: "",
		duringCombat: "",
		morale: "",
		gear: "",
		otherGear: "",
		note: "",
		characterFlag: 0,
		companionFlag: 0,
		canFly: 0,
		canClimb: 0,
		canBurrow: 0,
		canSwim: 0,
		canWalk: 1,
		templatesApplied: "",
		offenseNote: "",
		baseStatistics: "",
		extractsPrepared: "",
		ageCategory: "adult",
		dontUseRacialHD: 0,
		variantParent: "",
		mystery: "",
		classArchetypes: "",
		patron: "",
		alternateNameForm: "",
		statisticsNote: "",
		link: "",
		monsterId: 4092,
		mythicRating: 0,
		mythic: 0,
	},
];
